### ISSUE TITLE
question regarding the paratope-paratope interface of PDB:1N8Z

### ISSUE THREAD

**Issue by pengzhangzhi** [AbSciBio/unlocking-de-novo-antibody-design#1]
I would like to ask if the epitope-paratope binding interface in PDB:1N8Z is what you are working on. Did you redesign the paratope sequence that specifically binds to the epitope in PDB:1N8Z?

Best regards,

**Comment by ashane-absci** [comment]
Hi @pengzhangzhi. We designed the entire HCDR3 or HCDR123 of PDB:1N8Z (trastuzumab-HER2). That includes, but is not limited to, the relevant paratope residues contained in the HCDRs.
